"""empty message

Revision ID: 0e8ace4aad30
Revises: 1549ebd653f1
Create Date: 2020-08-27 15:20:41.587518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8ace4aad30'
down_revision = '1549ebd653f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hudong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aname', sa.String(length=20), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.Column('cont', sa.Text(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hudong')
    # ### end Alembic commands ###
