"""empty message

Revision ID: 1549ebd653f1
Revises: 7f7c440ebe0f
Create Date: 2020-08-27 15:18:06.220729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1549ebd653f1'
down_revision = '7f7c440ebe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hudong', 'hid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hudong', sa.Column('hid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
