"""empty message

Revision ID: 7b6fa1d9ab09
Revises: f6894ba073ba
Create Date: 2020-08-26 21:34:36.287083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6fa1d9ab09'
down_revision = 'f6894ba073ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hudong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aname', sa.String(length=20), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.Column('cont', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hudong')
    # ### end Alembic commands ###
