"""empty message

Revision ID: 7f7c440ebe0f
Revises: 7b6fa1d9ab09
Create Date: 2020-08-27 15:03:08.241119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7c440ebe0f'
down_revision = '7b6fa1d9ab09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hudong', sa.Column('hid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hudong', 'hid')
    # ### end Alembic commands ###
