"""empty message

Revision ID: 9da8df042ac2
Revises: 71b54b66d039
Create Date: 2020-08-27 19:53:59.609447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da8df042ac2'
down_revision = '71b54b66d039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('thumb_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'thumb_num')
    # ### end Alembic commands ###
