"""empty message

Revision ID: cbdf58eb376b
Revises: 9da8df042ac2
Create Date: 2020-08-28 11:37:24.396350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdf58eb376b'
down_revision = '9da8df042ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fans_num', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('follow_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'follow_num')
    op.drop_column('user', 'fans_num')
    # ### end Alembic commands ###
