"""empty message

Revision ID: f6894ba073ba
Revises: 1cdafe245a9b
Create Date: 2020-08-26 16:20:57.055422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6894ba073ba'
down_revision = '1cdafe245a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('essay', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'updated')
    op.drop_column('essay', 'created')
    # ### end Alembic commands ###
